name: Daily Discord Image

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:  # ← Add this line, it enables the manual run button

jobs:
  post-image:
    runs-on: ubuntu-latest
    steps:
      - name: Post image to Discord
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d '{
              "username": "Sleeper",
              "embeds": [{
                "title": "Goodnight.",
                "image": {
                  "url": "https://cdn.discordapp.com/attachments/1152319221523550298/1513757047022162030/bd4cf5f4b97d4370d444682204f920aa.png?ex=6a28e39c&is=6a27921c&hm=f1f6847e3362e00748ca9dc5fd34cfe3d064f10a7a20e640e2879dfa920ed9b3&"
                }
              }]
            }'
